### ISSUE TITLE
課題1

### ISSUE THREAD

**Issue by yuzaemon-lab** [yuzaemon-lab/lamp_practice#2]
SQLインジェクションに関して質問です。
例えば、以下の関数に対策をするとしたら、VALUESの変数を?にして、ステートメントに値をバインドする形式に書き換えればいいと思うのですが、その処理をexecute_query()で行っており、これを変更すると、他の関数に影響が出てしまいます。
この場合、”execute_query()関数を削除して、参照していた部分に追記していく”か、できるかわかりませんが、”bindValue(*, $*****,    PDO::PARAM_***)を配列に入れ、その配列の分だけfor文で$statement->配列[i];として繰り返す”のどちらかで対応しようと考えています。
どちらが一般的ですかね？
そもそも、後者って実装できそうですか？
ご教示願います。

function insert_cart($db, $item_id, $user_id, $amount = 1){
  $sql = "INSERT INTO carts(item_id, user_id, amount)
              VALUES({$item_id}, {$user_id}, {$amount})";
  return execute_query($db, $sql);
}

function execute_query($db, $sql, $params = array()){
  try{
    $statement = $db->prepare($sql);
    return $statement->execute($params);
  }catch(PDOException $e){
    set_error('更新に失敗しました。');
  }
  return false;
}

**Comment by manatago** [comment]
引数には初期値を設定しておくことができます。
例えば
function execute_query($db,$sql,$flag=false)
という感じ。

で、これを実行するときにexecute_query($db,$sql)で実行すれば$flagはfalseとして実行されます。

これを応用して、
第三引数に空の配列を初期値として入れといて、
もし第三引数の配列が空であればbindしない、 空でなければbindする、という感じになるかと思います。

**Comment by yuzaemon-lab** [comment]
一旦pushしましたが、商品管理のstatus変更ができなくなってしまい、以下のようなエラーが出ました。
db.php内のどこかがおかしいのだと思いますが、２時間くらいみてもわからなかったので、ご教示いただきたいです。

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: 
General error: 2031 in /var/www/model/db.php:49 
Stack trace: 
#0 /var/www/model/db.php(49): PDOStatement->execute(Array) 
#1 /var/www/model/item.php(110): execute_query(Object(PDO), '\n UPDATE\n ...', Array) 
#2 /var/www/html/admin_change_status.php(25): update_item_status(Object(PDO), '32', 1) 
#3 {main} thrown in /var/www/model/db.php on line 49

**Comment by manatago** [comment]
ふむ。一旦PULLしてみてみます。

**Comment by yuzaemon-lab** [comment]
$bindsを二次元配列にするとのことでしたが、いまいちピンときてません。。。
こんなイメージですか？
$binds = [
  [34(この数字何ですか？ただのキー？), "bindValue(1, $status_value, PDO::PARAM_INT)"],
  [45(同様), "bindValue(2, $item_id, PDO::PARAM_INT);"],
];
↓(execute_query()のtryの中)
$statement = $db->prepare($sql);
    if (isset($binds)) {
      foreach($binds as $rows) {
        foreach($rows as $bind) {
          eval('$statement->' . $bind . ';');
        }
      }
    }
    return $statement->execute();

**Comment by manatago** [comment]
昨日のSlackはわかりにくかったですね。申し訳ないです。

$bindsを定義するところでは
$binds=[
[$status_value,'int'],
[$item_id,'int']
]

関数の中では
$i=1;
foreach($binds as $val){
  if($val[1]==='int'){
    $statement->bindValue($i,$val[0],PDO::PARAM_INT);
  }else if ($val[1]==='str'){
    $statement->bindValue($i,$val[0],PDO::PARAM_STR);
  }
  $i++;
}
という感じです。

ピンとこなさそうであればここはレッスンのときんに話しましょう。
とりあえずはechoしているところを
eval(‘$statement->‘.$bind.‘;’);
に書き換える方法で進めてみてください。

危険性を理解した上で使うのであればevalは超絶便利です。

**Comment by yuzaemon-lab** [comment]
商品数の変更や削除はできるようになりましたが、やはりステータスの変更ができません。
（正確には、ステータス変更ボタンを押したら、更新成功のメッセージは出るのですが、ステータス変更はされない状況です。）
どこかでステータスがcloseになってるんですかね？

**Comment by manatago** [comment]
これ別の問題ですね。
item.phpの１６０行目あたりのこの関数、１の前後にシングルクォーテーションかダブルクォーテーションをつけて文字列にしとかないとダメです。
元のコードの問題かもしれないです。

function is_open($item){
  return $item['status'] === "1";
}
